### ISSUE TITLE
9 out of 10 requests return 502

### ISSUE THREAD

**Issue by ByronAP** [luminati-io/luminati-proxy#119] opened 2018-09-16 13:01 UTC
> byronap@w444444:~$ curl -i --proxy 127.0.0.1:24000 "http://lumtest.com/myip.json"
> HTTP/1.1 502 LPM - Bad Gateway
> Connection: close
> x-lpm-error: connect ECONNREFUSED 44.44.44.44:22225
> Date: Sun, 16 Sep 2018 12:55:36 GMT
> Transfer-Encoding: chunked

**Comment by fudali** [comment] 2018-09-25 08:44
How did you run luminati? Can you give us the whole command?

**Comment by ByronAP** [comment] 2018-09-25 13:41
I run in docker using startup cmd luminati 

> --no-dropin --www_whitelist_ips 10.240.0.9

**Comment by ByronAP** [comment] 2018-10-02 16:45
related to #129

**Comment by fudali** [comment] 2019-01-31 08:48
Hi. If this is still happening, please share with us your config file **(remember to erase the credentials)** and I'll try to reproduce the issue on our side. Once reproduced it will be fixed quickly

**Comment by fudali** [comment] 2019-03-26 16:25
closing due to inactivity

**Closed by fudali** 2019-03-26 16:25 UTC
Labels: more info needed

**Comment by jnu** [comment] 2019-04-20 16:27
Hi, I'm seeing this issue too. I don't see 502s connecting through `zproxy.lum-superproxy.io`, but only when I connect through LPM running locally.

Here is my config file (with passwords / names / IPs removed):

```
{
  "_defaults": {
    "customer": "xxxxxxxxxx",
    "password": [
      "************"
    ],
    "version": "1.131.652",
    "zone": "xxxxxxxx"
  },
  "proxies": [
    {
      "dns": "local",
      "ips": [
        "###.###.###.###",
        "###.###.###.###"
      ],
      "last_preset_applied": "custom",
      "max_requests": 0,
      "override_headers": true,
      "password": "************",
      "pool_size": 2,
      "port": 24000,
      "proxy_count": 5,
      "proxy_switch": 1,
      "random_user_agent": true,
      "session": false,
      "session_duration": 0,
      "ssl": true,
      "sticky_ip": true,
      "zone": "xxxxxxxx"
    }
  ]
}```

(Note I've played around with pool size and selecting different of my peer IPs and it doesn't solve the issue. Here I'm using two of my IPs that have high request success rate.

**Comment by sergshyn** [comment] 2019-04-23 12:06
Hi, the same for me, 
when working with LPM there are much more 502s responses that when using API directly.
