### ISSUE TITLE
--config parameter doesn't accept wildcards anymore (v0.7.31)

### ISSUE THREAD

**Issue by klunejko** [luminati-io/luminati-proxy#20] opened 2016-10-29 19:39 UTC
We're currently using v0.4.18 and are looking at upgrading to the latest version, however the config parameter doesn't appear to accept wildcards anymore.

Before, we could specify multiple config files, and pass them like this:
`--config=config/mx/41000/*.json`

In v0.7.31, the service starts with an empty config instead.

**Comment by lee-elenbaas** [comment] 2016-10-30 09:34
wild cards where never handled by the proxy-manager - they where handled by the shell
when i run with the arguments: --config config/mx/41000/*.json
i get all the files loaded - you you probably wanted to use just: config/mx/41000/*.json
to load the proxies without specifyin one of them as the main config file

in any case that = sign after --config should be removed

let me know if this solved your issue

**Comment by klunejko** [comment] 2016-10-30 18:35
Hm, whether I use it with `=` or without, doesn't seem to matter.

`/.json` doesn't work, and neither does `/*.json`. Only when I specify the specific config file does it pick up the config. Tried with .33 as well.

**Comment by lee-elenbaas** [comment] 2016-10-31 09:52
please contact me or some other luminati rep and have an online session to see the issue and resolve it

**Comment by lee-elenbaas** [comment] 2016-11-09 10:16
does this still reproduced for you?

**Comment by lee-elenbaas** [comment] 2016-11-27 13:01
since i don't get any response - i assume the issue does not repeat itself - and close it

**Closed by lee-elenbaas** 2016-11-27 13:01 UTC
Labels: help wanted
